[build]
  command = "npm install && cd frontend && npm install && npm run build"
  functions = "netlify/functions"
  publish = "frontend/build"

[build.environment]
  PYTHON_VERSION = "3.11"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
